package com.autonomy.pojo;

import java.io.Serializable;
import java.util.Date;

public class TyreUsers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.id
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.account
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.password
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.account_name
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.name
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.birthday
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.gender
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.email
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.salt
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.phone
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.language
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.country
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.province
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.city
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.area
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.street
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.detail_address
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.role_id
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.locked
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private Boolean locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.create_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.update_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.last_login_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.id
     *
     * @return the value of sys_users.id
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.id
     *
     * @param id the value for sys_users.id
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.account
     *
     * @return the value of sys_users.account
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.account
     *
     * @param account the value for sys_users.account
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.password
     *
     * @return the value of sys_users.password
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.password
     *
     * @param password the value for sys_users.password
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.account_name
     *
     * @return the value of sys_users.account_name
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.account_name
     *
     * @param accountName the value for sys_users.account_name
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.name
     *
     * @return the value of sys_users.name
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.name
     *
     * @param name the value for sys_users.name
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.birthday
     *
     * @return the value of sys_users.birthday
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.birthday
     *
     * @param birthday the value for sys_users.birthday
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.gender
     *
     * @return the value of sys_users.gender
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.gender
     *
     * @param gender the value for sys_users.gender
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.email
     *
     * @return the value of sys_users.email
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.email
     *
     * @param email the value for sys_users.email
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.salt
     *
     * @return the value of sys_users.salt
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.salt
     *
     * @param salt the value for sys_users.salt
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.phone
     *
     * @return the value of sys_users.phone
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.phone
     *
     * @param phone the value for sys_users.phone
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.language
     *
     * @return the value of sys_users.language
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.language
     *
     * @param language the value for sys_users.language
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.country
     *
     * @return the value of sys_users.country
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.country
     *
     * @param country the value for sys_users.country
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.province
     *
     * @return the value of sys_users.province
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.province
     *
     * @param province the value for sys_users.province
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.city
     *
     * @return the value of sys_users.city
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.city
     *
     * @param city the value for sys_users.city
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.area
     *
     * @return the value of sys_users.area
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.area
     *
     * @param area the value for sys_users.area
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.street
     *
     * @return the value of sys_users.street
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.street
     *
     * @param street the value for sys_users.street
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.detail_address
     *
     * @return the value of sys_users.detail_address
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.detail_address
     *
     * @param detailAddress the value for sys_users.detail_address
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.role_id
     *
     * @return the value of sys_users.role_id
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.role_id
     *
     * @param roleId the value for sys_users.role_id
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.locked
     *
     * @return the value of sys_users.locked
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.locked
     *
     * @param locked the value for sys_users.locked
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.create_time
     *
     * @return the value of sys_users.create_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.create_time
     *
     * @param createTime the value for sys_users.create_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.update_time
     *
     * @return the value of sys_users.update_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.update_time
     *
     * @param updateTime the value for sys_users.update_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.last_login_time
     *
     * @return the value of sys_users.last_login_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.last_login_time
     *
     * @param lastLoginTime the value for sys_users.last_login_time
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", accountName=").append(accountName);
        sb.append(", name=").append(name);
        sb.append(", birthday=").append(birthday);
        sb.append(", gender=").append(gender);
        sb.append(", email=").append(email);
        sb.append(", salt=").append(salt);
        sb.append(", phone=").append(phone);
        sb.append(", language=").append(language);
        sb.append(", country=").append(country);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", area=").append(area);
        sb.append(", street=").append(street);
        sb.append(", detailAddress=").append(detailAddress);
        sb.append(", roleId=").append(roleId);
        sb.append(", locked=").append(locked);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}