package com.autonomy.dao;

import com.autonomy.pojo.TyreUsers;

public interface TyreUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    int insert(TyreUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    int insertSelective(TyreUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    TyreUsers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    int updateByPrimaryKeySelective(TyreUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Sat Jun 06 12:45:20 CST 2020
     */
    int updateByPrimaryKey(TyreUsers record);
}